Add ability to customise the dismiss button's title
mergesort/Recap pull request #18
Opened 2024-10-23 09:36 UTC by iKenndac

This PR adds the ability to customise the title of the dismiss button via either a `LocalisedStringKey` (and optional bundle and table name) or a non-localised `String`.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/c3b6ef46-a86c-417f-a7d5-53e5341d4d4b">

One thing I'm unsure about is having the localised and non-localised variants have the same view modifier name - since `LocalisedStringKey` conforms to `ExpressibleByStringInterpolation` this may lead to some confusion.

2024-10-23 19:39 UTC, mergesort requested changes
I think my suggestion of switching to `LocalizedStringResource` would simplify quite a bit, and would solve the problem you raise of having localized and and non-localized variants of the `recapScreenDismissButtonTitle` modifier.

2024-10-23 19:39 UTC, mergesort commented on README.md
> +func recapScreenDismissButtonTitle(_ titleKey: LocalizedStringKey, in bundle: Bundle, tableName: String?) -> some View
I think we should use `LocalizedStringResource` here, rather than `LocalizedStringKey` with a bundle and table.

It would also provide us the benefit of removing `func recapScreenDismissButtonTitle(_ title: String)`, since `LocalizedStringResource` conforms to `ExpressibleByStringLiteral`.

2024-10-23 19:39 UTC, mergesort commented on Sources/Recap/Internal/RecapLocalizedStringKey.swift
> +struct RecapLocalizedStringKey {
I believe this could be removed as well if we use `LocalizedStringResource`.

2024-10-23 19:39 UTC, mergesort commented on Sources/Recap/Public/RecapScreen.swift
> +    @Environment(\.recapScreenDismissButtonTitle) private var dismissButtonCustomTitle
Let's name this `recapScreenDismissButtonTitle` to match the name in the Environment.

2024-10-24 08:16 UTC, iKenndac commented
@mergesort Couple of responses:

- Best I can tell, `LocalizedStringResource` is just like `LocalizedStringKey` in that the `ExpressibleByStringLiteral` conformance is used to give it the key. There isn't a way to make a non-localised `LocalizedStringKey` looking at the docs. I still think the `String` variant needs to be there for non-localised values.

- I think using `LocalizedStringResource` internally and having an API for clients for it makes sense.

- …however, we use `LocalizedStringKey` everywhere in our projects and that isn't going away overnight, so we'd need a `LocalizedStringKey` way of giving values to Recap. Annoyingly, as is SwiftUI's wont, these structs are all completely opaque and I can't see a way of making a `LocalizedStringResource` from a `LocalizedStringKey` - which means an extension with a translation shim doesn't seem to be possible.

2024-10-24 18:23 UTC, mergesort commented
> Best I can tell, LocalizedStringResource is just like LocalizedStringKey in that the ExpressibleByStringLiteral conformance is used to give it the key. There isn't a way to make a non-localised LocalizedStringKey looking at the docs. I still think the String variant needs to be there for non-localised values.

- I think this isn't necessarily intuitive, but a
`LocalizedStringResource` with no matching key will render the text as an unlocalized `String`.

If you look at [SwiftUI's Text](https://developer.apple.com/documentation/swiftui/text/init(_:)-1s6o1) you'll see that it takes a `LocalizedStringResource`. There is no initializer that takes a `String`, it will just render the `String` as is if it doesn't find a matching key.

That's why I'm proposing to remove the non-localized initializer, and follow the same pattern as SwiftUI does. I can confirm having done this many times in SwiftUI that the approach should work, and would be my preferred API design.

---

Separately: Feel free to reach out to me if you need a way to convert a `LocalizedStringKey` to a `LocalizedStringResource`, I have some code in Plinky that should make the transition easier for you.

2024-10-25 07:59 UTC, iKenndac commented
> a `LocalizedStringResource` with no matching key will render the text as an unlocalized String.

Technically correct, but also technically that's a broken key.

We can't switch to `LocalizedStringResource` because it's just not good enough for our uses. You can't even give it a bundle directly, instead having to do silly things like URL lookups [like this](https://github.com/mergesort/Recap/pull/18/commits/9358e05346f824862af152fe03ad796db6a51528#diff-16fc96d4d39c87683305f72040cf982522c54b75710157396b29f93297978b01R143). This has its uses, but that sort of lookup is far too slow for a whole catalog. `LocalizedStringResource` does have class-based lookup, but as far as I could see there isn't a single class in Recap, so I can't use that here (we can use it in our app, though).

The SwiftUI APIs keep around - without deprecation - `LocalizedStringKey` for good reason.

Anyway, I've removed everything but `LocalizedStringResource` as requested. We won't move to it in our codebases for the above reasons, but I can put up with it for one string.

2024-10-30 01:43 UTC, mergesort approved these changes
This looks great! Thank you so much for the implementation, and for making the requested changes. 🙇🏻‍♂️

2024-10-30 01:43 UTC, merged